version: "3.7"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn RT.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
#      - ./static_cdn/static/:/home/app/web/static
#      - ./static_cdn/media/:/home/app/web/media
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
    - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  redis:
    image: redis
    ports:
      - "6379:6379"
  nginx:
    build: ./nginx
    ports:
    - 1337:80
    volumes:
#      - ./static_cdn/static/:/static
#      - ./static_cdn/media/:/media
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - web
  celery:
    build: .
    command: celery -A RT worker -l INFO --pool=solo
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A RT beat
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - db
      - redis
volumes:
  pg_data:
  static_volume:
  media_volume: