version: "3.7"

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/usr/src/app
    ports:
    - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - eturate_pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_pass
      - POSTGRES_DB=django_eturate_dev
  redis:
    image: redis
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A RT worker -l INFO --pool=solo
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A RT beat
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - db
      - redis
volumes:
  eturate_pg_data: