# Generated by Django 3.1.6 on 2021-03-01 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(db_index=True, max_length=50, verbose_name='Отчество')),
                ('group_number', models.IntegerField(blank=True, null=True, verbose_name='Номер группы')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('birth_date', models.DateField(blank=True, default=None, verbose_name='Дата рождения')),
                ('is_student', models.BooleanField(default=False)),
                ('is_cathedra_head', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
