# Generated by Django 3.1.6 on 2021-03-24 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_auto_20210320_1424'),
        ('accounts', '0003_profile_cathedra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cathedra',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cathedra_heads', to='navigation.cathedra', verbose_name='Кафедра'),
        ),
    ]
