# Generated by Django 3.1.6 on 2021-04-27 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectivity_mark', models.IntegerField(default=0, verbose_name='Объективность оценивания')),
                ('knowledge_mark', models.IntegerField(default=0, verbose_name='Объём знаний по предмету')),
                ('communicability_mark', models.IntegerField(default=0, verbose_name='Связь с аудиторией')),
                ('load_mark', models.IntegerField(default=0, verbose_name='Требовательность')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Оценка преподавателя практики',
                'verbose_name_plural': 'Оценки преподавателей практики',
            },
        ),
        migrations.CreateModel(
            name='LectureReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectivity_mark', models.IntegerField(default=0, verbose_name='Объективность оценивания')),
                ('knowledge_mark', models.IntegerField(default=0, verbose_name='Объём знаний по предмету')),
                ('communicability_mark', models.IntegerField(default=0, verbose_name='Связь с аудиторией')),
                ('teacher_talent_mark', models.IntegerField(default=0, verbose_name='Умение дать материал')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Оценка преподавателя лектора',
                'verbose_name_plural': 'Оценки преподавателей лекторов',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_group_number', models.IntegerField(blank=True, null=True, verbose_name='Номер группы студента')),
                ('text', models.TextField(max_length=300, verbose_name='Текст комментария')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки комментария')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='CathedraReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attitude_to_student_mark', models.IntegerField(default=0, verbose_name='Отношение к студентам')),
                ('relevance_of_material_mark', models.IntegerField(default=0, verbose_name='Современность материала')),
                ('availability_of_cathedra_internship_mark', models.IntegerField(default=0, verbose_name='Возможность стажировки на кафедре')),
                ('find_job_opportunity_mark', models.IntegerField(default=0, verbose_name='Возможность найти работу')),
                ('cathedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.cathedra', verbose_name='Кафедра')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cathedra_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Оценка кафедры',
                'verbose_name_plural': 'Оценки кафедры',
            },
        ),
    ]
