# Generated by Django 3.1.6 on 2021-03-01 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectivity_mark', models.IntegerField(choices=[('Ужасно', 1), ('Плохо', 2), ('Нормально', 3), ('Хорошо', 4), ('Отлично', 5)], verbose_name='Объективность оценивания')),
                ('knowledge_mark', models.IntegerField(choices=[('Ужасно', 1), ('Плохо', 2), ('Нормально', 3), ('Хорошо', 4), ('Отлично', 5)], verbose_name='Объём знаний по предмету')),
                ('communicability_mark', models.IntegerField(choices=[('Ужасно', 1), ('Плохо', 2), ('Нормально', 3), ('Хорошо', 4), ('Отлично', 5)], verbose_name='Связь с аудиторией')),
                ('load_mark', models.IntegerField(choices=[('Ужасно', 1), ('Плохо', 2), ('Нормально', 3), ('Хорошо', 4), ('Отлично', 5)], verbose_name='Требовательность')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Студент')),
            ],
        ),
        migrations.CreateModel(
            name='LectureReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectivity_mark', models.IntegerField(choices=[('Ужасно', 1), ('Плохо', 2), ('Нормально', 3), ('Хорошо', 4), ('Отлично', 5)], verbose_name='Объективность оценивания')),
                ('knowledge_mark', models.IntegerField(choices=[('Ужасно', 1), ('Плохо', 2), ('Нормально', 3), ('Хорошо', 4), ('Отлично', 5)], verbose_name='Объём знаний по предмету')),
                ('communicability_mark', models.IntegerField(choices=[('Ужасно', 1), ('Плохо', 2), ('Нормально', 3), ('Хорошо', 4), ('Отлично', 5)], verbose_name='Связь с аудиторией')),
                ('teacher_talent_mark', models.IntegerField(choices=[('Ужасно', 1), ('Плохо', 2), ('Нормально', 3), ('Хорошо', 4), ('Отлично', 5)], verbose_name='Умение дать материал')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Студент')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_group_number', models.IntegerField(verbose_name='Номер группы студента')),
                ('text', models.TextField(max_length=300, verbose_name='Текст комментария')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки комментария')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Студент')),
            ],
        ),
    ]
