# Generated by Django 3.1.6 on 2021-04-26 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturereview',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата оценки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicereview',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата оценки'),
            preserve_default=False,
        ),
    ]
