# Generated by Django 3.1.6 on 2021-03-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cathedrareview',
            options={'verbose_name': 'Оценка кафедры', 'verbose_name_plural': 'Оценки кафедры'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='lecturereview',
            options={'verbose_name': 'Оценка препоадвателя лектора', 'verbose_name_plural': 'Оценки препоадвателей лекторов'},
        ),
        migrations.AlterModelOptions(
            name='practicereview',
            options={'verbose_name': 'Оценка препоадвателя практики', 'verbose_name_plural': 'Оценки препоадвателей практики'},
        ),
    ]
