# Generated by Django 3.1.6 on 2021-03-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210320_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturereview',
            options={'verbose_name': 'Оценка преподавателя лектора', 'verbose_name_plural': 'Оценки преподавателей лекторов'},
        ),
        migrations.AlterModelOptions(
            name='practicereview',
            options={'verbose_name': 'Оценка преподавателя практики', 'verbose_name_plural': 'Оценки преподавателей практики'},
        ),
    ]
