# Generated by Django 3.1.6 on 2021-03-01 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
        ('reviews', '0002_auto_20210301_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='navigation.teacher', verbose_name='Преподаватель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturereview',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='navigation.teacher', verbose_name='Преподаватель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicereview',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='navigation.teacher', verbose_name='Преподаватель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecturereview',
            name='communicability_mark',
            field=models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Связь с аудиторией'),
        ),
        migrations.AlterField(
            model_name='lecturereview',
            name='knowledge_mark',
            field=models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Объём знаний по предмету'),
        ),
        migrations.AlterField(
            model_name='lecturereview',
            name='objectivity_mark',
            field=models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Объективность оценивания'),
        ),
        migrations.AlterField(
            model_name='lecturereview',
            name='teacher_talent_mark',
            field=models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Умение дать материал'),
        ),
        migrations.AlterField(
            model_name='practicereview',
            name='communicability_mark',
            field=models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Связь с аудиторией'),
        ),
        migrations.AlterField(
            model_name='practicereview',
            name='knowledge_mark',
            field=models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Объём знаний по предмету'),
        ),
        migrations.AlterField(
            model_name='practicereview',
            name='load_mark',
            field=models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Требовательность'),
        ),
        migrations.AlterField(
            model_name='practicereview',
            name='objectivity_mark',
            field=models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Объективность оценивания'),
        ),
    ]
