# Generated by Django 3.1.6 on 2021-03-02 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_auto_20210302_1427'),
        ('reviews', '0003_auto_20210302_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='CathedraReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attitude_to_student_mark', models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Отношение к студентам')),
                ('relevance_of_material_mark', models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Современность материала')),
                ('availability_of_cathedra_internship_mark', models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Возможность стажировки на кафедре')),
                ('find_job_opportunity_mark', models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Возможность найти работу')),
                ('cathedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.cathedra', verbose_name='Кафедра')),
            ],
        ),
    ]
