# Generated by Django 3.1.6 on 2021-04-17 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cathedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название кафедры')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Ссылка на кафедру')),
                ('info', models.TextField(blank=True, max_length=500, verbose_name='Описание кафедры')),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='cathedra_logos/', verbose_name='Логотип кафедры')),
                ('attitude_to_student_mark', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Отношение к студентам')),
                ('relevance_of_material_mark', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Современность материала')),
                ('availability_of_cathedra_internship_mark', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Возможность стажировки на кафедре')),
                ('find_job_opportunity_mark', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Возможность найти работу')),
                ('teachers_mark', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Оценка преподавателей кафедры')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название факультета')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Ссылка на факультет')),
                ('info', models.TextField(default=None, max_length=500, verbose_name='Описание факультета')),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='faculty_logos/', verbose_name='Логотип факультета')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(db_index=True, max_length=50, verbose_name='Отчество')),
                ('speciality', models.CharField(db_index=True, max_length=50, verbose_name='Специальность')),
                ('avatar', models.ImageField(blank=True, default='avatar.png', upload_to='teachers_avatars/', verbose_name='Фотография преподавателя')),
                ('is_lecturer', models.BooleanField(default=True)),
                ('is_practical', models.BooleanField(default=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('objectivity_lecture_mark', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Объективность оценивания (Лектор)')),
                ('objectivity_practice_mark', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Объективность оценивания (Практик)')),
                ('knowledge_lecture_mark', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Объём знаний по предмету (Лектор)')),
                ('knowledge_practice_mark', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Объём знаний по предмету (Практик)')),
                ('communicability_lecture_mark', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Связь с аудиторией (Лектор)')),
                ('communicability_practice_mark', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Связь с аудиторией (Практик)')),
                ('teacher_talent_mark', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Умение дать материал')),
                ('load_mark', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Требовательность')),
                ('cathedras', models.ManyToManyField(related_name='teachers', to='navigation.Cathedra', verbose_name='Кафедры преподавателей')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название курса')),
                ('teachers', models.ManyToManyField(related_name='courses', to='navigation.Teacher', verbose_name='Преподаватели курсов')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.AddField(
            model_name='cathedra',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cathedras', to='navigation.faculty', verbose_name='Факультет'),
        ),
    ]
