# Generated by Django 3.1.6 on 2021-03-01 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cathedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Название кафедры')),
                ('slug', models.SlugField(verbose_name='Ссылка на кафедру')),
                ('attitude_to_student_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Отношение к студентам')),
                ('relevance_of_material_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Современность материала')),
                ('availability_of_cathedra_internship_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Возможность стажировки на кафедре')),
                ('find_job_opportunity_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Возможность найти работу')),
                ('teachers_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Оценка преподавателей кафедры')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Название факультета')),
                ('slug', models.SlugField(verbose_name='Ссылка на факультет')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(db_index=True, max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(db_index=True, max_length=50, verbose_name='Отчество')),
                ('speciality', models.CharField(db_index=True, max_length=50, verbose_name='Специальность')),
                ('is_lecturer', models.BooleanField(default=True)),
                ('is_practical', models.BooleanField(default=True)),
                ('birth_date', models.DateField(blank=True, default=None, verbose_name='Дата рождения')),
                ('objectivity_lecture_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Объективность оценивания (Лектор)')),
                ('objectivity_practice_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Объективность оценивания (Практик)')),
                ('knowledge_lecture_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Объём знаний по предмету (Лектор)')),
                ('knowledge_practice_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Объём знаний по предмету (Практик)')),
                ('communicability_lecture_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Связь с аудиторией (Лектор)')),
                ('communicability_practice_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Связь с аудиторией (Практик)')),
                ('communicability_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Связь с аудиторией (Лектор)')),
                ('teacher_talent_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Умение дать материал')),
                ('load_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Требовательность')),
                ('cathedra', models.ManyToManyField(related_name='teacher', to='navigation.Cathedra', verbose_name='Кафедры преподавателей')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Название курса')),
                ('slug', models.SlugField(verbose_name='Ссылка на курс')),
                ('teachers', models.ManyToManyField(related_name='courses', to='navigation.Teacher', verbose_name='Преподаватели курсов')),
            ],
        ),
        migrations.AddField(
            model_name='cathedra',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.faculty', verbose_name='Факультет'),
        ),
    ]
