# Generated by Django 3.1.6 on 2021-03-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='cathedra',
            field=models.ManyToManyField(related_name='teachers', to='navigation.Cathedra', verbose_name='Кафедры преподавателей'),
        ),
    ]
