# Generated by Django 3.1.6 on 2021-04-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathedra',
            name='info',
            field=models.TextField(blank=True, max_length=400, verbose_name='Описание кафедры'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='info',
            field=models.TextField(default=None, max_length=400, verbose_name='Описание факультета'),
        ),
    ]
