# Generated by Django 3.1.6 on 2021-04-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_auto_20210320_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathedra',
            name='info',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание кафедры'),
        ),
    ]
