# Generated by Django 3.1.6 on 2021-04-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_auto_20210406_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathedra',
            name='title',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название кафедры'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='title',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название факультета'),
        ),
    ]
