# Generated by Django 3.1.6 on 2021-03-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_auto_20210310_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Ссылка на факультет'),
        ),
    ]
