# Generated by Django 3.1.6 on 2021-03-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_auto_20210312_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathedra',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Ссылка на кафедру'),
        ),
    ]
