# Generated by Django 3.1.6 on 2021-03-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_auto_20210312_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.png', upload_to='teachers_avatars/', verbose_name='Фотография преподавателя'),
        ),
    ]
