# Generated by Django 3.1.6 on 2021-03-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0006_auto_20210313_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathedra',
            name='attitude_to_student_mark',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Отношение к студентам'),
        ),
        migrations.AlterField(
            model_name='cathedra',
            name='availability_of_cathedra_internship_mark',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Возможность стажировки на кафедре'),
        ),
        migrations.AlterField(
            model_name='cathedra',
            name='find_job_opportunity_mark',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Возможность найти работу'),
        ),
        migrations.AlterField(
            model_name='cathedra',
            name='relevance_of_material_mark',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Современность материала'),
        ),
        migrations.AlterField(
            model_name='cathedra',
            name='teachers_mark',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Оценка преподавателей кафедры'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='communicability_lecture_mark',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Связь с аудиторией (Лектор)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='communicability_practice_mark',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Связь с аудиторией (Практик)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='knowledge_lecture_mark',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Объём знаний по предмету (Лектор)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='knowledge_practice_mark',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Объём знаний по предмету (Практик)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='load_mark',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Требовательность'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='objectivity_lecture_mark',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Объективность оценивания (Лектор)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='objectivity_practice_mark',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Объективность оценивания (Практик)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_talent_mark',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Умение дать материал'),
        ),
    ]
