# Generated by Django 3.1.6 on 2021-03-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0008_auto_20210313_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathedra',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='cathedra_logos/', verbose_name='Логотип кафедры'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='faculty_logos/', verbose_name='Логотип факультета'),
        ),
    ]
